{{- $signingSecretName := default (printf "%s-signing" (include "knowledge-fabric.fullname" .)) .Values.security.signingKey.existingSecret -}}
{{- if not .Values.security.signingKey.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $signingSecretName }}
  labels:
    {{- include "knowledge-fabric.labels" . | nindent 4 }}
type: Opaque
data:
  fabric-signing-key: {{ .Values.security.signingKey.value | b64enc | quote }}
---
{{- end }}

{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knowledge-fabric.fullname" . }}-postgres
  labels:
    {{- include "knowledge-fabric.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
---
{{- end }}

{{- if and .Values.ai.openai.apiKey (not .Values.ai.openai.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knowledge-fabric.fullname" . }}-openai
  labels:
    {{- include "knowledge-fabric.labels" . | nindent 4 }}
type: Opaque
data:
  openai-api-key: {{ .Values.ai.openai.apiKey | b64enc | quote }}
---
{{- end }}
